### ISSUE TITLE
Webilder

### ISSUE THREAD

**Issue by tleeonly** [thesamet/webilder#24] opened 2011-08-30 20:10 UTC
I get this message that says Error occured while downloading images Unable to download webshots_d3287304.jpg what is the problem and how can I fix it. thanks

**Comment by thesamet** [comment] 2011-08-30 20:13
Try to run webilder_downloader (or WebilderDownloader) from the command line and send me any input you get.

**Comment by tleeonly** [comment] 2011-08-30 20:20
Here it is webilder_downloader
Downloading list of photos (may take some time) 
url =  http://api.flickr.com/services/rest/?sort=interestingness-desc&extras=original_format&tag_mode=all&tags=landscapes&per_page=20&api_key=045379bc5368502f749af23d95a17c83&method=flickr.photos.search
Filtering photos (may take some time) 
Skipping banned photo 'The Helix Bridge in Marina Bay, Singapore :: HDR'.
Skipping already existing photo 'when heaven and earth collide'
Skipping already existing photo 'Light gash in november sky'
Skipping already existing photo 'Frisian Winter Wonderland'
Skipping banned photo 'SINGAPORE  MARINA BAY SANDS link Double HELIX BRIDGE'.
Skipping already existing photo 'Samone...tramonto sul fondovalle  (guiglia modena italy)_4937-Flickr'
Skipping banned photo 'Stepping Stones over the River Mole, Box Hill, Dorking'.
url =  http://api.flickr.com/services/rest/?api_key=045379bc5368502f749af23d95a17c83&photo_id=4275025746&method=flickr.photos.getInfo
url =  http://api.flickr.com/services/rest/?api_key=045379bc5368502f749af23d95a17c83&photo_id=4275025746&method=flickr.photos.getSizes
Skipping non-landscape photo 'My Backyard + NY Blizzard = Winter Wonderland - IMRAN™ Stunning, snow filled landscape at Sunset. 2800+ Views 430+ Comments!'
url =  http://api.flickr.com/services/rest/?api_key=045379bc5368502f749af23d95a17c83&photo_id=4090074382&method=flickr.photos.getInfo
url =  http://api.flickr.com/services/rest/?api_key=045379bc5368502f749af23d95a17c83&photo_id=4090074382&method=flickr.photos.getSizes
Skipping non-landscape photo 'Lovebirds....'
Skipping already existing photo 'Autumn Sunrise in the forest of childhood dreams, nothing has changed ... in the forest - Missano , Via Fontanazzo.. (zocca modena italy)'
Skipping already existing photo 'Missano Via Fontanazzo Autunno 2009 -(zocca modena italy)- 0746 - Flickr'
Skipping banned photo 'Landscape: Blue Sunflowers in Italy'.
Skipping already existing photo 'Fog  -  autumn - ( zocca modena italy)'
Skipping already existing photo 'Landscape: Yellow Summer and blue sky.'
Skipping already existing photo 'Sparks Lake, Oregon - HDR'
Skipping banned photo 'le vele.... Italy 2009'.
url =  http://api.flickr.com/services/rest/?api_key=045379bc5368502f749af23d95a17c83&photo_id=3865775996&method=flickr.photos.getInfo
url =  http://api.flickr.com/services/rest/?api_key=045379bc5368502f749af23d95a17c83&photo_id=3865775996&method=flickr.photos.getSizes
Skipping non-landscape photo 'Tresche Conca-Vicenza-Italy 2009'
Skipping banned photo 'London Cardinal Place :: “The real voyage of discovery consists not in seeking new landscapes but in having new eyes.” ~'.
url =  http://api.flickr.com/services/rest/?api_key=045379bc5368502f749af23d95a17c83&photo_id=3677452765&method=flickr.photos.getInfo
url =  http://api.flickr.com/services/rest/?api_key=045379bc5368502f749af23d95a17c83&photo_id=3677452765&method=flickr.photos.getSizes
Skipping non-landscape photo 'Landscape: Winter Dress is green and blue.'
Skipping banned photo 'Landscape: Along the Road in Green, Blue and Orange'.
webshots: Downloading 'Maddalena Archipelago, Near Sardinia, Italy'
Traceback (most recent call last):
  File "/usr/bin/webilder_downloader", line 9, in <module>
    load_entry_point('Webilder==0.7.1', 'console_scripts', 'webilder_downloader')()
  File "/usr/lib/pymodules/python2.7/webilder/downloader.py", line 195, in main
    download_all(notify)
  File "/usr/lib/pymodules/python2.7/webilder/downloader.py", line 165, in download_all
    memfile = download_photo(config, photo, download_notifier)
  File "/usr/lib/pymodules/python2.7/webilder/downloader.py", line 99, in download_photo
    stream = photo['_plugin']['module'].get_photo_stream(config_obj, photo)
  File "/usr/lib/pymodules/python2.7/webilder/webshots/utils.py", line 126, in get_photo_stream
    raise ValueError, "Unable to download photo %s" % photo['name']
ValueError: Unable to download photo webshots_d3287304.jpg

--- On Tue, 8/30/11, thesamet reply@reply.github.com wrote:

**Comment by thesamet** [comment] 2011-08-30 20:31
Thanks for reporting. It looks like webshots.com changed their pages in a way that doesn't let Webilder download from it. This happens from time to time. I'll fix it and update the bug.

**Comment by tleeonly** [comment] 2011-08-30 21:07
Thank you, yours truly, Harvey 

--- On Tue, 8/30/11, thesamet reply@reply.github.com wrote:

**Comment by thesamet** [comment] 2011-11-13 03:00
It appears like this problem can not be reproduced. Closing for now.

**Closed as completed by thesamet** 2011-11-13 03:00 UTC

**Comment by purpleleaf** [comment] 2011-12-09 15:16
i encountered the same problem... i will open another issue.

**Comment by purpleleaf** [comment] 2011-12-09 15:36
discovered now that only premium users can download pictures from webshots :(

**Comment by tleeonly** [comment] 2011-12-09 23:17
Okay so we all know what that means. oh well 

--- On Fri, 12/9/11, purpleleaf reply@reply.github.com wrote:
